export enum PagePath {
  Home = '/',
  SignIn = '/signin',
  SignUp = '/signup',
  SignOut = '/signout',
  Time = '/time',
  TimeRecord = '/time/record',
  TimeRecordByUser = '/time/record/:id',
  TimeAnalysis = '/time/analysis',
  Admin = '/admin',
  AdminRole = '/admin/role',
  AdminCredentials = '/admin/credentials',
  User = '/user',
  Project = '/project',
  ProjectCustomer = 'project/customer',
  ProjectCategory = 'project/category',
  ProjectBusinessCategory = '/project/category/business',
  ProjectIndustryCategory = '/project/category/industry',
  ProjectTaskCategory = '/project/category/task',
  Setting = '/setting',
}
