export enum PagePath {
  Home = '/',
  Wating = '/wating',
  Rejected = '/rejected',
  Disabled = '/disabled',
  MyPage = '/mypage',
  SignIn = '/signin',
  SignUp = '/signup',
  SignOut = '/signout',
  Time = '/time',
  TimeRecord = '/time/record',
  TimeRecordByUser = '/time/record/:id',
  TimeAnalysis = '/time/analysis',
  Developer = '/developer',
  Admin = '/admin',
  AdminRole = '/admin/role',
  AdminCredentials = '/admin/credentials',
  AdminSetting = '/admin/setting',
  User = '/user',
  Project = '/project',
  ProjectList = '/project/list',
  ProjectCustomer = '/project/customer',
  ProjectCategory = '/project/category',
  ProjectBusinessCategory = '/project/category/business',
  ProjectIndustryCategory = '/project/category/industry',
  ProjectTaskCategory = '/project/category/task',
}
