name: Develop

on:
  push:
    branches: ['develop']
    paths-ignore: ['*.md']

jobs:
  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: Asia/Seoul

      - name: Install dependencies
        run: |
          npm ci

      - name: Create environments
        env:
          ENV: ${{ secrets.ENV_DEVELOP }}
          TAG: ${{ github.ref_name }}
        run: |
          rm .env*
          echo "$ENV" >> .env
          echo "REACT_APP_VERSION=$TAG_$(date +'%Y-%m-%d_%H:%M:%S')" >> .env

      - name: Build application
        run: |
          npm run build
          cp build/index.html build/404.html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 sync build s3://$S3_BUCKET/develop \
            --acl bucket-owner-full-control

      - name: Invalidate cloundfront cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID_DEVELOP }}
          PATHS: /*
