name: Github Pages

on:
  push:
    branches: ['develop']
    paths-ignore: ['*.md']

jobs:
  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Create environments
        env:
          ENV: ${{ secrets.ENV_DEVELOP }}
          TAG: ${{ github.ref_name }}
        run: |
          rm .env
          echo "$ENV" >> .env
          echo "VERSION=$TAG$(date +'%Y-%m-%d_%H:%M:%S')" >> .env

      - name: Add homepage into package.json
        run: |
          node scripts/gh-pages.js

      - name: Build application
        run: |
          npm run build
          cp build/index.html build/404.html

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build
